//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.IO;
using System.Data.SQLite;

public class PreProcessor
{
    public static void ProcessTables(StreamReader reader)
    {

        string rawSql = reader.ReadToEnd();
        TableProccessor.CreateAndFillTable(rawSql);
    }
    
    public static void LoadTableAndPreprocess()
    {

        TableProccessor.RetrieveTable();
        TableProccessor.CalculateColumnProperties();
        TableProccessor.Process();
    }

	public static void ProccessWorkload(StreamReader Workload)
	{
        string temp = Workload.ReadToEnd();
        SQLQuery[] queries = WorkloadParser.Parse(temp);
        WorkloadProcessor.Process(queries);
	}

}

