//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class TableCreator
{
    public static Table table;

	public static DatabaseConnection dbConnection
	{
		get;
		set;
	}

	public static Table FillTable(List<string> Sql)
	{
		throw new System.NotImplementedException();
	}

	public static void CreateTable(string table)
	{
        throw new System.NotImplementedException();
    }

}

