//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Table
{
	public Row[] Rows
	{
		get;
		set;
	}

	/// <summary>
	/// Column type definition
	/// </summary>
	public String[] Columns
	{
		get;
		set;
	}

	public Row Row
	{
		get;
		set;
	}

}

