//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class WorkloadProcessor
{
    

    /// <summary>
    /// here the QF similarities should be calculated
    /// </summary>
    /// <param name="Workload"></param>
	public static void Process(SQLQuery[] Workload)
	{
		throw new System.NotImplementedException();
	}

}

