//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq; 
using System.Text;

public class MetaDbFiller
{
    public Table table;
	

public List<Table> MetaTable;

    public DatabaseConnection dbConnection;

	public  void PostQF(int table, decimal[,] Qfs)
	{
		throw new System.NotImplementedException();
	}

	public  void CreateMetaTable( Table MetaTable)
	{
		throw new System.NotImplementedException();
	}

}

