//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class TableCreator
{
	public virtual  DatabaseConnection dbConnection
	{
		get;
		set;
	}

	public virtual Table FillTable(string[] Sql)
	{
		throw new System.NotImplementedException();
	}

	public virtual void CreateTable(string table)
	{
		throw new System.NotImplementedException();
	}

}

