//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class WorkloadProcessor
{
	public static int[] GetTableDimensioins(int tableId, int ColumnId)
	{
		throw new System.NotImplementedException();
	}

	public void Process()
	{
		throw new System.NotImplementedException();
	}

}

